version: '3.1'

services:

  postgres_service:
    image: postgres:12-alpine
    restart: always
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
    ports:
      - 8577:5432


